# Generated by Django 4.1.7 on 2023-04-01 08:54

from django.db import migrations, models
import upsheershak.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file_key', models.CharField(max_length=256)),
                ('lang_codes', models.CharField(max_length=128)),
                ('is_processed', models.BooleanField(default=False)),
                ('key', models.CharField(max_length=8)),
                ('file', models.FileField(upload_to=upsheershak.models.modify_filename)),
                ('last_modified', models.DateTimeField()),
                ('created_on', models.DateTimeField()),
            ],
        ),
    ]
