# Generated by Django 4.1.7 on 2023-04-01 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upsheershak', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filerequest',
            name='audio_file_key',
        ),
    ]
