# Generated by Django 4.1.7 on 2023-04-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upsheershak', '0002_remove_filerequest_audio_file_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='filerequest',
            name='detected_lang',
            field=models.CharField(default='', max_length=4),
        ),
    ]
